# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/f/Bionluk/Nuray

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/f/Bionluk/Nuray/cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/f/Bionluk/Nuray/cmake-build-debug/CMakeFiles /mnt/f/Bionluk/Nuray/cmake-build-debug/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/f/Bionluk/Nuray/cmake-build-debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Nuray_Algo

# Build rule for target.
Nuray_Algo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nuray_Algo
.PHONY : Nuray_Algo

# fast build rule for target.
Nuray_Algo/fast:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/build
.PHONY : Nuray_Algo/fast

algorithmA.o: algorithmA.cpp.o

.PHONY : algorithmA.o

# target to build an object file
algorithmA.cpp.o:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmA.cpp.o
.PHONY : algorithmA.cpp.o

algorithmA.i: algorithmA.cpp.i

.PHONY : algorithmA.i

# target to preprocess a source file
algorithmA.cpp.i:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmA.cpp.i
.PHONY : algorithmA.cpp.i

algorithmA.s: algorithmA.cpp.s

.PHONY : algorithmA.s

# target to generate assembly for a file
algorithmA.cpp.s:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmA.cpp.s
.PHONY : algorithmA.cpp.s

algorithmB.o: algorithmB.cpp.o

.PHONY : algorithmB.o

# target to build an object file
algorithmB.cpp.o:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmB.cpp.o
.PHONY : algorithmB.cpp.o

algorithmB.i: algorithmB.cpp.i

.PHONY : algorithmB.i

# target to preprocess a source file
algorithmB.cpp.i:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmB.cpp.i
.PHONY : algorithmB.cpp.i

algorithmB.s: algorithmB.cpp.s

.PHONY : algorithmB.s

# target to generate assembly for a file
algorithmB.cpp.s:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmB.cpp.s
.PHONY : algorithmB.cpp.s

algorithmC.o: algorithmC.cpp.o

.PHONY : algorithmC.o

# target to build an object file
algorithmC.cpp.o:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmC.cpp.o
.PHONY : algorithmC.cpp.o

algorithmC.i: algorithmC.cpp.i

.PHONY : algorithmC.i

# target to preprocess a source file
algorithmC.cpp.i:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmC.cpp.i
.PHONY : algorithmC.cpp.i

algorithmC.s: algorithmC.cpp.s

.PHONY : algorithmC.s

# target to generate assembly for a file
algorithmC.cpp.s:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmC.cpp.s
.PHONY : algorithmC.cpp.s

algorithmD.o: algorithmD.cpp.o

.PHONY : algorithmD.o

# target to build an object file
algorithmD.cpp.o:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmD.cpp.o
.PHONY : algorithmD.cpp.o

algorithmD.i: algorithmD.cpp.i

.PHONY : algorithmD.i

# target to preprocess a source file
algorithmD.cpp.i:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmD.cpp.i
.PHONY : algorithmD.cpp.i

algorithmD.s: algorithmD.cpp.s

.PHONY : algorithmD.s

# target to generate assembly for a file
algorithmD.cpp.s:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmD.cpp.s
.PHONY : algorithmD.cpp.s

algorithmE.o: algorithmE.cpp.o

.PHONY : algorithmE.o

# target to build an object file
algorithmE.cpp.o:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmE.cpp.o
.PHONY : algorithmE.cpp.o

algorithmE.i: algorithmE.cpp.i

.PHONY : algorithmE.i

# target to preprocess a source file
algorithmE.cpp.i:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmE.cpp.i
.PHONY : algorithmE.cpp.i

algorithmE.s: algorithmE.cpp.s

.PHONY : algorithmE.s

# target to generate assembly for a file
algorithmE.cpp.s:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmE.cpp.s
.PHONY : algorithmE.cpp.s

algorithmF.o: algorithmF.cpp.o

.PHONY : algorithmF.o

# target to build an object file
algorithmF.cpp.o:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmF.cpp.o
.PHONY : algorithmF.cpp.o

algorithmF.i: algorithmF.cpp.i

.PHONY : algorithmF.i

# target to preprocess a source file
algorithmF.cpp.i:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmF.cpp.i
.PHONY : algorithmF.cpp.i

algorithmF.s: algorithmF.cpp.s

.PHONY : algorithmF.s

# target to generate assembly for a file
algorithmF.cpp.s:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmF.cpp.s
.PHONY : algorithmF.cpp.s

algorithmG.o: algorithmG.cpp.o

.PHONY : algorithmG.o

# target to build an object file
algorithmG.cpp.o:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmG.cpp.o
.PHONY : algorithmG.cpp.o

algorithmG.i: algorithmG.cpp.i

.PHONY : algorithmG.i

# target to preprocess a source file
algorithmG.cpp.i:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmG.cpp.i
.PHONY : algorithmG.cpp.i

algorithmG.s: algorithmG.cpp.s

.PHONY : algorithmG.s

# target to generate assembly for a file
algorithmG.cpp.s:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmG.cpp.s
.PHONY : algorithmG.cpp.s

algorithmH.o: algorithmH.cpp.o

.PHONY : algorithmH.o

# target to build an object file
algorithmH.cpp.o:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmH.cpp.o
.PHONY : algorithmH.cpp.o

algorithmH.i: algorithmH.cpp.i

.PHONY : algorithmH.i

# target to preprocess a source file
algorithmH.cpp.i:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmH.cpp.i
.PHONY : algorithmH.cpp.i

algorithmH.s: algorithmH.cpp.s

.PHONY : algorithmH.s

# target to generate assembly for a file
algorithmH.cpp.s:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmH.cpp.s
.PHONY : algorithmH.cpp.s

algorithmI.o: algorithmI.cpp.o

.PHONY : algorithmI.o

# target to build an object file
algorithmI.cpp.o:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmI.cpp.o
.PHONY : algorithmI.cpp.o

algorithmI.i: algorithmI.cpp.i

.PHONY : algorithmI.i

# target to preprocess a source file
algorithmI.cpp.i:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmI.cpp.i
.PHONY : algorithmI.cpp.i

algorithmI.s: algorithmI.cpp.s

.PHONY : algorithmI.s

# target to generate assembly for a file
algorithmI.cpp.s:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/algorithmI.cpp.s
.PHONY : algorithmI.cpp.s

helpers.o: helpers.cpp.o

.PHONY : helpers.o

# target to build an object file
helpers.cpp.o:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/helpers.cpp.o
.PHONY : helpers.cpp.o

helpers.i: helpers.cpp.i

.PHONY : helpers.i

# target to preprocess a source file
helpers.cpp.i:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/helpers.cpp.i
.PHONY : helpers.cpp.i

helpers.s: helpers.cpp.s

.PHONY : helpers.s

# target to generate assembly for a file
helpers.cpp.s:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/helpers.cpp.s
.PHONY : helpers.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/main.cpp.s
.PHONY : main.cpp.s

testerQ3.o: testerQ3.cpp.o

.PHONY : testerQ3.o

# target to build an object file
testerQ3.cpp.o:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/testerQ3.cpp.o
.PHONY : testerQ3.cpp.o

testerQ3.i: testerQ3.cpp.i

.PHONY : testerQ3.i

# target to preprocess a source file
testerQ3.cpp.i:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/testerQ3.cpp.i
.PHONY : testerQ3.cpp.i

testerQ3.s: testerQ3.cpp.s

.PHONY : testerQ3.s

# target to generate assembly for a file
testerQ3.cpp.s:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/testerQ3.cpp.s
.PHONY : testerQ3.cpp.s

testerQ4.o: testerQ4.cpp.o

.PHONY : testerQ4.o

# target to build an object file
testerQ4.cpp.o:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/testerQ4.cpp.o
.PHONY : testerQ4.cpp.o

testerQ4.i: testerQ4.cpp.i

.PHONY : testerQ4.i

# target to preprocess a source file
testerQ4.cpp.i:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/testerQ4.cpp.i
.PHONY : testerQ4.cpp.i

testerQ4.s: testerQ4.cpp.s

.PHONY : testerQ4.s

# target to generate assembly for a file
testerQ4.cpp.s:
	$(MAKE) -f CMakeFiles/Nuray_Algo.dir/build.make CMakeFiles/Nuray_Algo.dir/testerQ4.cpp.s
.PHONY : testerQ4.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Nuray_Algo"
	@echo "... algorithmA.o"
	@echo "... algorithmA.i"
	@echo "... algorithmA.s"
	@echo "... algorithmB.o"
	@echo "... algorithmB.i"
	@echo "... algorithmB.s"
	@echo "... algorithmC.o"
	@echo "... algorithmC.i"
	@echo "... algorithmC.s"
	@echo "... algorithmD.o"
	@echo "... algorithmD.i"
	@echo "... algorithmD.s"
	@echo "... algorithmE.o"
	@echo "... algorithmE.i"
	@echo "... algorithmE.s"
	@echo "... algorithmF.o"
	@echo "... algorithmF.i"
	@echo "... algorithmF.s"
	@echo "... algorithmG.o"
	@echo "... algorithmG.i"
	@echo "... algorithmG.s"
	@echo "... algorithmH.o"
	@echo "... algorithmH.i"
	@echo "... algorithmH.s"
	@echo "... algorithmI.o"
	@echo "... algorithmI.i"
	@echo "... algorithmI.s"
	@echo "... helpers.o"
	@echo "... helpers.i"
	@echo "... helpers.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... testerQ3.o"
	@echo "... testerQ3.i"
	@echo "... testerQ3.s"
	@echo "... testerQ4.o"
	@echo "... testerQ4.i"
	@echo "... testerQ4.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

